kafka:
  bootstrap-servers: 'http://kafka-broker-2:9092'
  topic: 'test'
  consumer-group-id: 'mail-consumer'

server:
  port: 8082

management:
  metrics:
    export:
      influx:
        db: kafkamailsender
        uri: http://influxdb:8086
        user-name: admin
        password: admin
        auto-create-db: false
        step: 10s