version: '3.7'

services:
  kafka-zookeeper-2:
    container_name: kafka-zookeeper-2
    hostname: kafka-zookeeper-2
    restart: unless-stopped
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zk-data:/data

  kafka-broker-2:
    container_name: kafka-broker-2
    hostname: kafka-broker-2
    restart: unless-stopped
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-broker-2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper-2:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-data:/data

  producer:
    container_name: 'kafka-producer'
    build:
      context: .
      dockerfile: ./kafka-producer/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - kafka-broker-2
    environment:
      KAFKA_BOOTSTRAP-SERVERS: 'http://kafka-broker-2:9092'
      KAFKA_TOPIC: 'test'

  mail:
    container_name: 'kafka-mail-sender'
    build:
      context: .
      dockerfile: ./kafka-mail-sender/Dockerfile
    ports:
      - '8082:8080'
    depends_on:
      - kafka-broker-2
    environment:
      KAFKA_BOOTSTRAP-SERVERS: 'http://kafka-broker-2:9092'
      KAFKA_TOPIC: 'test'
      KAFKA_CONUSMER-GROUP-ID: 'mail-sender'

  sms:
    container_name: 'kafka-sms-sender'
    build:
      context: .
      dockerfile: ./kafka-sms-sender/Dockerfile
    ports:
      - '8084:8080'
    depends_on:
      - kafka-broker-2
    environment:
      KAFKA_BOOTSTRAP-SERVERS: 'http://kafka-broker-2:9092'
      KAFKA_TOPIC: 'test'
      KAFKA_CONUSMER-GROUP-ID: 'sms-sender'
