global:
  scrape_interval: '5s'
  evaluation_interval: '5s'

scrape_configs:
  - job_name: 'kafka-producer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['kafka-producer:8080']