# config file version
apiVersion: 1

datasources:
  - name: kafka-mail-sender-influxdb
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    user: admin
    password: admin
    database: kafkamailsender
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpMode: GET
      timeInterval: "10s"
  - name: kafka-sms-sender-influxdb
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    user: admin
    password: admin
    database: kafkasmssender
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpMode: GET
      timeInterval: "10s"