kafka:
  bootstrap-servers: 'http://kafka-broker-2:9092'
  topic: 'test'

server:
  port: 8080

spring:
  application:
    name: 'kafka-producer'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

external:
  weather:
    api:
      url: 'https://community-open-weather-map.p.rapidapi.com'
      key: '5302094e51msh67c13d06da94b67p1a51dbjsnad6db2ccfe51'
      host: 'community-open-weather-map.p.rapidapi.com'